version: "3.9"

services:
  api:
    build: ./packages/gitflat-api
    ports:
      - "${PORT_API}:4000"
    environment:
      - GIT_TOKEN=${GIT_TOKEN}
  client:
    build: ./packages/gitflat-client
    ports:
      - "${PORT_CLIENT}:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:4000/gitflat